### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by jeroenptrs** [nos/visual-identity#3]
* [x] Be smart about responsiveness, many tabs will flood the tab bar but 
* [ ] Since tabs are up top, this is also where the **window controls** live. Make sure you think about macOS vs Windows vs Linux distributions

## Mobile / Tablet
* [ ] How do other mobile browsers do this and can we learn from this?
* [ ] Do they persist on scrolling?

**Comment by fabric-8** [comment]
Tabs are being addressed as part of browser controls in #4
